name: SOOS Core SCA
on: push
jobs:
  soos_sca:
    name: SOOS SCA Scan
    runs-on: ubuntu-latest
    steps:
      - uses: soos-io/soos-sca-github-action@v1.0.3-beta
        name: SOOS SCA Scan
        with:
          project_name: ${{ github.repository }}
          branch_name: ${{ github.ref }}
          commit_hash: ${{ github.sha }}
          sarif: true
          gpat: ${{ secrets.SOOS_GITHUB_PAT }}
        env:
          # Visit https://soos.io to get the required tokens to leverage SOOS scanning/analysis services
          SOOS_CLIENT_ID: ${{ secrets.SOOS_CLIENT_ID }}
          SOOS_API_KEY: ${{ secrets.SOOS_API_KEY }}
          SOOS_GITHUB_PAT: ${{ secrets.SOOS_GITHUB_PAT }}
