name: SOOS Core SCA
on: push
jobs:
  soos_sca:
    name: SOOS SCA Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: soos-io/soos-sca-github-action@v1.0.4
        name: SOOS SCA Scan
        with:
          project_name: ${{ github.repository }}
          sarif: true
          gpat: ${{ secrets.SOOS_GPAT }}
          # Visit https://soos.io to get the required tokens to leverage SOOS scanning/analysis services
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
